USE [MOV]
GO

/****** Object:  StoredProcedure [dbo].[SP_LISTA_MOVIMENTO_MANUAL]    Script Date: 03/07/2018 23:48:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_LISTA_MOVIMENTO_MANUAL]
AS
SELECT M.DAT_MES,
       M.DAT_ANO,
	   M.NUM_LANCAMENTO,
	   P.COD_PRODUTO,
	   P.DES_PRODUTO,
	   PC.COD_COSIF,
	   M.VAL_VALOR,
	   M.DES_DESCRICAO AS DESCR_MOVIMENTO,
	   M.DAT_MOVIMENTO
  FROM PRODUTO P INNER JOIN PRODUTO_COSIF PC ON P.COD_PRODUTO = PC.COD_PRODUTO
       INNER JOIN MOVIMENTO_MANUAL M ON P.COD_PRODUTO = M.COD_PRODUTO AND PC.COD_PRODUTO = M.COD_PRODUTO
	   AND PC.COD_COSIF = M.COD_COSIF
 ORDER BY M.DAT_MES, M.DAT_ANO, M.NUM_LANCAMENTO
GO


