USE [MOV]
GO

/****** Object:  Table [dbo].[PRODUTO_COSIF]    Script Date: 03/07/2018 23:46:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PRODUTO_COSIF](
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF] [char](11) NOT NULL,
	[COD_CLASSIFICACAO] [char](6) NULL,
	[STA_STATUS] [char](1) NULL,
 CONSTRAINT [PK_PRODUTO_COSIF] PRIMARY KEY CLUSTERED 
(
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PRODUTO_COSIF]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO] FOREIGN KEY([COD_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([COD_PRODUTO])
GO

ALTER TABLE [dbo].[PRODUTO_COSIF] CHECK CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO]
GO


